name: Test_iOS

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Install Qt
    uses: jurplel/install-qt-action@v2
    with:
      version: 5.12.6
      target: ios
      host: mac
      install-deps: true
    
    - name: Tree
      run: tree
