name: Test_DesktopWinMSVC

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Install Qt
        # Action from https://github.com/jurplel/install-qt-action
        #Temporarily using ouuan/install-qt-action@v2.3.1 until jurplel has bug fix implemented
        uses: ouuan/install-qt-action@v2.3.1
        
      - name: list Qt bin
        run: ls D:/a/EMOM_Timer/Qt/5.12.6/msvc2017_64/bin
        
      - name: Search for MSVC 2017
        run: |
          set PATH=D:\a\EMOM_Timer\Qt\5.12.6\msvc2017_64\bin;%PATH%
          echo %PATH%
          cd /d "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build"
          dir
          call vcvarsall.bat x64
          cl
        shell: cmd
          
        
      #- name: Run vcvarsall.bat
      #  run: |
      #    cd /d "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\"
      #    dir
      #    call vcvarsall.bat x86
      #    echo "Run dir and cl"
      #    dir
      #    cl
      #  shell: cmd

      #- name: Print nmake version
      # run: nmake/?
      - name: Build hello.cpp
        run: |
          echo %PATH%
          cd D:\a\EMOM_Timer\EMOM_Timer\Test
          qmake -project
          dir
          qmake
          nmake
          dir
        shell: cmd
