name: Test_DesktopWinMSVC

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Install Qt
        # Action from https://github.com/jurplel/install-qt-action
        #Temporarily using ouuan/install-qt-action@v2.3.1 until jurplel has bug fix implemented
        uses: ouuan/install-qt-action@v2.3.1      

      #- name: Print nmake version
      # run: nmake/?
      - name: Build hello.cpp
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl
          dir %Qt5_Dir%/lib/cmake
          cd /d D:\a\EMOM_Timer\EMOM_Timer\Test
          qmake -project
          qmake
          nmake
          dir
          dir release
        shell: cmd
