name: Test_DesktopWinMSVC

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Install Qt
        # Action from https://github.com/jurplel/install-qt-action
        uses: jurplel/install-qt-action@v2.4.0    

      #- name: Print nmake version
      # run: nmake/?
      - name: Build hello.cpp
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          echo %Qt5_Dir%
          cd /d D:\a\EMOM_Timer\EMOM_Timer\Test
          qmake -project
          qmake
          nmake
          cd release
          Test.exe
        shell: cmd
