name: Test_DesktopWinMSVC

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      #- name: Install developer command prompt for microsoft visual c++
      #  uses: ilammy/msvc-dev-cmd@v1
       
      - name: Install Qt
        # Action from https://github.com/jurplel/install-qt-action
        #Temporarily using ouuan/install-qt-action@v2.3.1 until jurplel has bug fix implemented
        uses: ouuan/install-qt-action@v2.3.1
        
      - name: list Qt bin
        run: ls
        
      #- name: Run vcvarsall.bat
       # run: |
        #  ls 'C:\Program Files (x86)\Microsoft Visual Studio 14.0' -R
         # 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
          #cd 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64'
          #ls
          #.\vcvars64.bat
      
      - name: Print out program files dir
        run: |
          ls 'C:\Program Files (x86)\'
          ls 'C:\Program Files\'

      #- name: Print nmake version
      # run: nmake/?
      - name: Build hello.cpp
        run: |
          cd D:\a\EMOM_Timer\EMOM_Timer\Test
          qmake -project
          echo "Post qmake commands"
          ls
