name: Test_DesktopWin

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Qt
        # Action from https://github.com/jurplel/install-qt-action
        #Temporarily using ouuan/install-qt-action@v2.3.1 until jurplel has bug fix implemented
        uses: ouuan/install-qt-action@v2.3.1
        
      - name: Print out Qt directory
        run: echo %Qt5_Dir%

      - name: Print out qmake version
        run: qmake --version

      - name: dir cmd
        run: dir D:/a/EMOM_Timer/EMOM_Timer/
      
      - name: Build hello.cpp
        run: |
          cd D:\a\EMOM_Timer\EMOM_Timer\Test
          dir
          qmake -project
          dir
          qmake
          dir
          make
          dir
          ./hello.cpp
