name: Test_DesktopWin

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      #- name: Install developer command prompt for microsoft visual c++
      #  uses: ilammy/msvc-dev-cmd@v1
       
      - name: Install Qt
        # Action from https://github.com/jurplel/install-qt-action
        #Temporarily using ouuan/install-qt-action@v2.3.1 until jurplel has bug fix implemented
        uses: ouuan/install-qt-action@v2.3.1
        with:
          arch: win64_mingw73
        
      - name: Print out Qt directory
        run: echo %Qt5_Dir%

      - name: Print out qmake version
        run: qmake --version

      - name: ls cmd
        run: ls 'C:\Program Files (x86)\'
        
      - name: Build hello.cpp
        run: |
          cd D:\a\EMOM_Timer\EMOM_Timer\Test
          qmake -project
          qmake
          echo "Post qmake commands"
          ls
          
      - name: Upload Makefile
        uses: actions/upload-artifact@v1
        with: 
            name: makefile
            path: D:\a\EMOM_Timer\EMOM_Timer\Test\Makefile
            
      - name: Run make
        run: |
          cd D:\a\EMOM_Timer\EMOM_Timer\Test
          make
          ls 
          ls -R
          echo "try executing"
          cd D:\a\EMOM_Timer\EMOM_Timer\Test\release
          ./Test
          
      - name: Upload Exe
        uses: actions/upload-artifact@v1
        with:
          name: Test.exe
          path: D:\a\EMOM_Timer\EMOM_Timer\Test\release\Test.exe
